create table if not exists public.analysis_history (
  id bigint generated by default as identity primary key,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.analysis_history enable row level security;
